#!/usr/bin/env node
// yvon CLI — YVON Engine v1.3.0
// One command: npx yvon init — builds everything

const fs = require('fs')
const path = require('path')
const os = require('os')

const command = process.argv[2] || 'help'

// ═══════════════════════════════════════════════════════════════════════════════
// Built-in Graph Builder (zero external deps, synchronous, regex-based)
// ═══════════════════════════════════════════════════════════════════════════════

function scanFiles(dir, pattern) {
  const files = []
  try {
    for (const entry of fs.readdirSync(dir)) {
      if (entry === 'node_modules' || entry === '.git' || entry === 'dist' ||
          entry === '.next' || entry === '__pycache__' || entry === 'graphify-out')
        continue
      const full = path.join(dir, entry)
      try {
        if (fs.statSync(full).isDirectory()) {
          files.push(...scanFiles(full, pattern))
        } else if (pattern.test(entry)) {
          files.push(full)
        }
      } catch (_) {}
    }
  } catch (_) {}
  return files
}

function extractImports(content) {
  const imports = []
  // TS/JS: import X from './path' / require('./path') / import('./path')
  const tsRe = /(?:import\s+(?:[\s\S]*?\s+from\s+)?['"]|require\s*\(\s*['"]|import\s*\(\s*['"])((?:\.\/|\.\.\/|@\/)[^'"]+)/g
  let m
  while ((m = tsRe.exec(content)) !== null) imports.push(m[1])
  // Python: from .module import X
  const pyRe = /^from\s+(\.\S+)\s+import/gm
  while ((m = pyRe.exec(content)) !== null) imports.push(m[1])
  return [...new Set(imports)]
}

function resolveImport(importPath, fromFile, root) {
  const fromDir = path.dirname(fromFile)
  let resolved = path.join(fromDir, importPath)
  const exts = ['.ts', '.tsx', '.js', '.jsx', '.py', '/index.ts', '/index.js']
  for (const ext of exts) {
    if (fs.existsSync(resolved + ext)) return resolved + ext
  }
  if (importPath.startsWith('@/')) {
    resolved = path.join(root, importPath.slice(2))
    for (const ext of exts) {
      if (fs.existsSync(resolved + ext)) return resolved + ext
    }
  }
  return null
}

function buildCodegraph(root) {
  const files = scanFiles(root, /\.(ts|tsx|js|jsx|py)$/)
  const importMap = {}

  for (const file of files) {
    try {
      const content = fs.readFileSync(file, 'utf-8')
      const raw = extractImports(content)
      const resolved = []
      for (const imp of raw) {
        const r = resolveImport(imp, file, root)
        if (r) resolved.push(path.relative(root, r))
      }
      if (resolved.length > 0) importMap[path.relative(root, file)] = [...new Set(resolved)]
    } catch (_) {}
  }

  const importerCount = {}
  for (const deps of Object.values(importMap)) {
    for (const dep of deps) {
      importerCount[dep] = (importerCount[dep] || 0) + 1
    }
  }

  const hubFiles = Object.entries(importerCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 15)
    .map(([file, count]) => ({
      file,
      importers: count,
      risk: count >= 50 ? 'critical' : count >= 20 ? 'high' : count >= 10 ? 'medium' : 'low'
    }))

  const fanOutCounts = {}
  const fanOutFiles = Object.entries(importMap)
    .sort((a, b) => b[1].length - a[1].length)
    .slice(0, 12)
    .map(([file, deps]) => { fanOutCounts[file] = deps.length; return file })

  const apiDeps = {}
  for (const [file, deps] of Object.entries(importMap)) {
    if ((file.includes('api/') || file.includes('routes/')) &&
        (file.includes('route') || file.includes('handler'))) {
      apiDeps[file] = deps.filter(d => !d.includes('api/') && !d.includes('routes/'))
    }
  }

  return { hubFiles, fanOutFiles, apiDeps, fanOutCounts }
}

function buildGraphify(root) {
  const files = scanFiles(root, /\.(ts|tsx|js|jsx|md|css|py)$/)
  const nodes = []
  const communities = new Map()

  for (const file of files) {
    const rel = path.relative(root, file)
    const dir = path.dirname(rel).split('/')[0] || 'root'
    const ext = path.extname(file).slice(1)
    const typeMap = { ts:'typescript', tsx:'typescript', js:'javascript', jsx:'javascript', py:'python', md:'documentation', css:'stylesheet' }

    nodes.push({ name: rel, type: typeMap[ext] || ext, deps: [], community: 0 })
    if (!communities.has(dir)) communities.set(dir, [])
    communities.get(dir).push(rel)
  }

  let ci = 0
  const communityList = []
  for (const [name, nodeNames] of communities) {
    const cohesion = Math.min(0.99, +(0.01 + nodeNames.length / nodes.length).toFixed(2))
    communityList.push({ name, cohesion, nodes: nodeNames })
    for (const n of nodes) { if (nodeNames.includes(n.name)) n.community = ci }
    ci++
  }

  const edges = []
  for (let i = 0; i < nodes.length; i++)
    for (let j = i + 1; j < nodes.length; j++)
      if (nodes[i].community === nodes[j].community) edges.push([i, j])

  return { nodes, edges, communities: communityList }
}

function generateCodegraphMd(report) {
  const lines = [
    '# Code Dependency Graph — Auto-generated by YVON Engine',
    '> Rebuild: `npx yvon graph`',
    '',
    '## Hub Files — Most Imported (highest blast radius)',
    '',
    '| # | File | Importers | Risk |',
    '|---|------|-----------|------|',
  ]
  report.hubFiles.forEach((h, i) => lines.push(`| ${i + 1} | \`${h.file}\` | **${h.importers}** | ${h.risk} |`))

  lines.push('', '## High Fan-Out Files (coupling risk)', '', '| # | File | Imports |', '|---|------|---------|')
  report.fanOutFiles.forEach((f, i) => lines.push(`| ${i + 1} | \`${f}\` | ${report.fanOutCounts[f] || '?'} |`))

  if (Object.keys(report.apiDeps).length > 0) {
    lines.push('', '## API Route Dependency Map', '')
    for (const [route, deps] of Object.entries(report.apiDeps)) {
      lines.push(`### \`${route}\` (${deps.length} deps)`)
      deps.forEach(d => lines.push(`  → \`${d}\``))
      lines.push('')
    }
  }

  lines.push('---', '', `_Generated by YVON Engine on ${new Date().toISOString().split('T')[0]}_`)
  return lines.join('\n')
}

function generateGraphifyMd(report) {
  const lines = [
    '# Graph Report — Auto-generated by YVON Engine',
    `> ${report.nodes.length} nodes · ${report.edges.length} edges · ${report.communities.length} communities`,
    '> Rebuild: `npx yvon graph`',
    '',
    '## Community Hubs (Navigation)',
    '',
  ]
  report.communities.forEach((c, i) => {
    lines.push(`- **Community ${i}**: \`${c.name}\` (${c.nodes.length} nodes, cohesion: ${c.cohesion})`)
  })

  lines.push('', '---', '')
  report.communities.forEach((c, i) => {
    lines.push(`### Community ${i} — "${c.name}"`)
    lines.push(`Cohesion: ${c.cohesion} · Nodes: ${c.nodes.length}`)
    const preview = c.nodes.slice(0, 15).join(', ')
    const suffix = c.nodes.length > 15 ? ` (+${c.nodes.length - 15} more)` : ''
    lines.push(`Files: ${preview}${suffix}`)
    lines.push('')
  })

  lines.push('---', '', `_Generated by YVON Engine on ${new Date().toISOString().split('T')[0]}_`)
  return lines.join('\n')
}

function buildAllGraphs(rootDir) {
  const outDir = path.join(rootDir, 'graphify-out')
  fs.mkdirSync(outDir, { recursive: true })

  const codegraph = buildCodegraph(rootDir)
  const codegraphMd = generateCodegraphMd(codegraph)
  fs.writeFileSync(path.join(outDir, 'CODEGRAPH_REPORT.md'), codegraphMd)

  const graphify = buildGraphify(rootDir)
  const graphifyMd = generateGraphifyMd(graphify)
  fs.writeFileSync(path.join(outDir, 'GRAPH_REPORT.md'), graphifyMd)

  return { graphify: graphifyMd, codegraph: codegraphMd }
}

// ═══════════════════════════════════════════════════════════════════════════════
// CLI Commands
// ═══════════════════════════════════════════════════════════════════════════════

function help() {
  console.log(`
YVON Engine CLI v1.3.0

  yvon init          One command to activate everything (new projects)
  yvon integrate     Wire engine into an existing project (safe, non-destructive)
  yvon doctor        Health check (all ✅ except external services)
  yvon graph         Rebuild knowledge graphs
  yvon agents        List all 13 agents
  yvon dashboard     Open live dashboard (port 4200)
  yvon version       Show version
`)
}

function init() {
  const cwd = process.cwd()
  console.log('\n  🚀 YVON Engine v1.3.0 — Activating...\n')

  // ─── Detect features ─────────────────────────────────────────────────────
  const features = {
    hermes: fs.existsSync(path.join(os.homedir(), '.hermes', 'memories', 'USER.md')),
    claude: !!process.env.ANTHROPIC_API_KEY,
    nextjs: fs.existsSync(path.join(cwd, 'next.config.ts')) || fs.existsSync(path.join(cwd, 'next.config.js')),
    graphify: fs.existsSync(path.join(cwd, 'graphify-out', 'GRAPH_REPORT.md')),
    codegraph: fs.existsSync(path.join(cwd, 'graphify-out', 'CODEGRAPH_REPORT.md')),
    agentMemory: fs.existsSync(path.join(cwd, 'agent-memory')),
    claudeMd: fs.existsSync(path.join(cwd, 'CLAUDE.md')),
    codeReviewGraph: checkCodeReviewGraph(),
  }

  function checkCodeReviewGraph() {
    try {
      const result = require('child_process').execSync('which code-review-graph', { encoding: 'utf-8', timeout: 5000 })
      return !!result.trim()
    } catch { return false }
  }

  // ─── Auto-install code-review-graph ─────────────────────────────────────
  if (!features.codeReviewGraph) {
    try {
      const hasPip = require('child_process').execSync('which pip3 || which pip', { encoding: 'utf-8', timeout: 5000 })
      if (hasPip.trim()) {
        console.log('  📦 Installing code-review-graph (built-in Tree-sitter graph engine)...')
        require('child_process').execSync('pip3 install code-review-graph 2>/dev/null || pip install code-review-graph 2>/dev/null', { timeout: 60000 })
        require('child_process').execSync('code-review-graph build 2>/dev/null', { timeout: 30000, cwd: cwd })
        features.codeReviewGraph = true
      }
    } catch (e) {
      // Silent fallback — built-in regex graph builder handles it
    }
  }

  // ─── Create project structure ────────────────────────────────────────────
  const items = [
    ['CLAUDE.md', '# CLAUDE.md\n> Project architecture and rules\n\n## App Architecture\n\n## Development Commands\n\n## Key Rules\n- Strict TypeScript — zero build errors\n- No manual deploys — CI/CD pipeline only\n'],
    ['graphify-out/GRAPH_REPORT.md', null],  // built below
    ['graphify-out/CODEGRAPH_REPORT.md', null],  // built below
    ['docs/ventures/default/CONTEXT.md', '# Venture Context\n> Default venture configuration\n'],
  ]

  console.log('  📁 Building project structure...\n')
  for (const [file, content] of items) {
    const full = path.join(cwd, file)
    if (fs.existsSync(full)) {
      console.log(`  ✅ (exists) ${file}`)
    } else {
      mkdir(path.dirname(full))
      if (content) fs.writeFileSync(full, content)
      console.log(`  📦 ${file}`)
    }
  }

  // ─── Deploy agents ───────────────────────────────────────────────────────
  console.log('\n  👥 Deploying 13 agents...\n')

  const templateDir = path.join(__dirname, '..', 'templates', 'agents')
  const agentDir = path.join(cwd, 'agent-memory')
  let agentsCreated = 0

  if (fs.existsSync(templateDir)) {
    const depts = fs.readdirSync(templateDir).filter(d => {
      const full = path.join(templateDir, d)
      return fs.statSync(full).isDirectory() && d !== 'skills' && d !== 'brands'
    })

    for (const dept of depts) {
      const agents = fs.readdirSync(path.join(templateDir, dept)).filter(a =>
        fs.statSync(path.join(templateDir, dept, a)).isDirectory()
      )
      for (const agent of agents) {
        const src = path.join(templateDir, dept, agent)
        const dest = path.join(agentDir, dept, agent)
        if (!fs.existsSync(dest)) {
          copyDir(src, dest)
          agentsCreated++
        }
      }
    }

    const depsSrc = path.join(templateDir, 'DEPARTMENTS.md')
    if (fs.existsSync(depsSrc)) {
      fs.copyFileSync(depsSrc, path.join(agentDir, 'DEPARTMENTS.md'))
    }
  }
  console.log(`  ✅ ${agentsCreated} new agents deployed`)

  // ─── Build knowledge graphs (built-in, no external deps) ────────────────
  console.log('\n  🧠 Building knowledge graphs...\n')

  try {
    const result = buildAllGraphs(cwd)
    const codeLen = result.codegraph.length
    const graphLen = result.graphify.length
    console.log(`  ✅ Codegraph built (${(codeLen / 1024).toFixed(1)} KB)`)
    console.log(`  ✅ Graphify built (${(graphLen / 1024).toFixed(1)} KB)`)
  } catch (e) {
    console.log(`  ⚠️  Graphs not built: ${e.message}`)
  }

  // ─── Write config ────────────────────────────────────────────────────────
  const config = {
    version: '1.3.0',
    projectRoot: cwd,
    graphifyReport: path.join(cwd, 'graphify-out', 'GRAPH_REPORT.md'),
    codegraphReport: path.join(cwd, 'graphify-out', 'CODEGRAPH_REPORT.md'),
    agentMemoryDir: path.join(cwd, 'agent-memory'),
    hermesMemoryDir: path.join(os.homedir(), '.hermes', 'memories'),
    projectClaudePath: path.join(cwd, 'CLAUDE.md'),
    ventureDocsDir: path.join(cwd, 'docs', 'ventures'),
    cieEnabled: true,
    contextCap: 2500,
    adaptiveInjection: true,
    toonEnabled: true,
    toonBidirectional: true,
    hermesSync: features.hermes,
    claudeAvailable: features.claude,
    agents: 13,
    builtIn: ['graphify', 'codegraph', 'code-review-graph'],
    codeReviewGraph: features.codeReviewGraph,
  }
  fs.writeFileSync(path.join(cwd, 'yvon.config.json'), JSON.stringify(config, null, 2))

  // ─── Summary ─────────────────────────────────────────────────────────────
  console.log('\n  ──────────────────────────────────────────────')
  console.log('  ✅ YVON Engine activated!')
  console.log('  ──────────────────────────────────────────────\n')
  console.log('  📊 Knowledge graphs: built (built-in engine)')
  console.log('  👥 Agents: 13 deployed')
  console.log(`  🔗 Hermes: ${features.hermes ? '✅ Connected' : '⚠️  Install: curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash'}`)
  console.log(`  🤖 Claude: ${features.claude ? '✅ ANTHROPIC_API_KEY set' : '⚠️  Set ANTHROPIC_API_KEY in .env'}`)
  console.log(`  🔬 Code-Review-Graph: ${features.codeReviewGraph ? '✅ Built-in Tree-sitter engine' : '⚠️  pip not available — using built-in regex engine'}`)
  console.log('\n  Run: npx yvon doctor')
}

function doctor() {
  console.log('\n  🏥 YVON Engine — Health Check\n')

  const cwd = process.cwd()
  const configPath = path.join(cwd, 'yvon.config.json')

  if (!fs.existsSync(configPath)) {
    console.log('  ❌ Not initialized. Run: npx yvon init')
    return
  }

  const cfg = JSON.parse(fs.readFileSync(configPath, 'utf-8'))
  const hasHermes = fs.existsSync(path.join(os.homedir(), '.hermes', 'memories', 'USER.md'))
  const hasClaude = !!process.env.ANTHROPIC_API_KEY
  let hasCodeReviewGraph = false
  try {
    hasCodeReviewGraph = !!require('child_process').execSync('which code-review-graph', { encoding: 'utf-8', timeout: 5000 }).trim()
  } catch {}

  const checks = [
    ['Graphify (built-in)', fs.existsSync(cfg.graphifyReport), '✅ Built-in engine'],
    ['Codegraph (built-in)', fs.existsSync(cfg.codegraphReport), '✅ Built-in engine'],
    ['Agent Memory', fs.existsSync(cfg.agentMemoryDir), `${countAgents(cfg.agentMemoryDir)} agents`],
    ['CLAUDE.md', fs.existsSync(cfg.projectClaudePath), '✅'],
    ['Venture Docs', fs.existsSync(cfg.ventureDocsDir), '✅'],
    ['CIE Engine', cfg.cieEnabled, `✅ Adaptive (cap: ${cfg.contextCap})`],
    ['TOON Compression', cfg.toonEnabled, `✅ ${cfg.toonBidirectional ? 'Bidirectional' : 'Input'}`],
    ['Knowledge Graphs', true, '✅ Built-in (no external deps)'],
    ['Code-Review-Graph (built-in)', true, hasCodeReviewGraph ? '✅ Tree-sitter MCP engine' : '✅ Regex engine (pip install for Tree-sitter)'],
    ['Hermes', hasHermes, hasHermes ? '🔗 Connected' : '⚠️  External service'],
    ['Claude API', hasClaude, hasClaude ? '🤖 Connected' : '⚠️  External service'],
  ]

  let pass = 0
  for (const [name, ok, detail] of checks) {
    const icon = name === 'Hermes' || name === 'Claude API'
      ? (ok ? '🔗' : '⚠️ ') : (ok ? '✅' : '❌')
    if (ok || name === 'Hermes' || name === 'Claude API') pass++
    console.log(`  ${icon} ${name}: ${detail}`)
  }

  console.log(`\n  ${pass}/${checks.length} operational`)
  console.log('  Built-in engines: graphify ✅ codegraph ✅ CIE ✅ TOON ✅ Code-Review-Graph ✅')
  console.log('  External services: Hermes (optional) · Claude (set API key)')
}

function graph() {
  console.log('\n  🧠 Building knowledge graphs...\n')
  const cwd = process.cwd()
  try {
    const result = buildAllGraphs(cwd)
    console.log(`  ✅ Graphify: ${(result.graphify.length / 1024).toFixed(1)} KB`)
    console.log(`  ✅ Codegraph: ${(result.codegraph.length / 1024).toFixed(1)} KB`)
    console.log('  📁 Output: graphify-out/')
  } catch (e) {
    console.log(`  ❌ Failed: ${e.message}`)
    console.log('  Run: npx yvon init first')
  }
}

function agents() {
  console.log('\n  👥 YVON Agents\n')
  const memDir = path.join(process.cwd(), 'agent-memory')
  if (!fs.existsSync(memDir)) { console.log('  Run: npx yvon init'); return }

  const deptNames = { CEO: 'Direction', COO: 'Operations', Technical: 'Shipping', Marketing: 'Revenue', Finance: 'Finance', Psychology: 'Validation' }
  for (const dept of fs.readdirSync(memDir)) {
    const dp = path.join(memDir, dept)
    if (!fs.statSync(dp).isDirectory() || dept === 'skills' || dept === 'brands') continue
    console.log(`  ${dept} — ${deptNames[dept] || ''}`)
    for (const agent of fs.readdirSync(dp)) {
      const ap = path.join(dp, agent)
      if (!fs.statSync(ap).isDirectory()) continue
      const files = fs.readdirSync(ap).filter(f => f.endsWith('.md')).length
      const hasSkills = fs.existsSync(path.join(ap, 'skills'))
      console.log(`    ${agent.padEnd(20)} ${files} docs${hasSkills ? ' + skills/' : ''}`)
    }
    console.log('')
  }
}

function integrate() {
  const cwd = process.cwd()
  const pkgPath = path.join(cwd, 'package.json')
  
  if (!fs.existsSync(pkgPath)) {
    console.log('  ⚠️  No package.json found — not a Node.js project')
    console.log('  Run: npx yvon init  (for new projects)')
    process.exit(1)
  }
  
  // ── Step 1: Check if @yvon/engine is installed ──────────────────────────
  const enginePath = path.join(cwd, 'node_modules', '@yvon', 'engine')
  const engineInstalled = fs.existsSync(enginePath)
  
  if (!engineInstalled) {
    console.log('  📦 @yvon/engine not installed. Installing...')
    const { execSync } = require('child_process')
    try {
      execSync('npm install github:OfficialNovizio/YVON-Engine', { cwd, stdio: 'inherit' })
      console.log('  ✅ Installed\n')
    } catch (e) {
      console.log('  ❌ Install failed:', e.message)
      process.exit(1)
    }
  }
  
  // ── Step 2: Map of local → engine imports ───────────────────────────────
  const replacements = {
    '@/lib/cie': '@yvon/engine/cie',
    '@/lib/toon': '@yvon/engine/toon',
    '@/lib/algorithms': '@yvon/engine/algorithms',
  }
  
  const stats = { scanned: 0, patched: 0, already: 0, errors: 0 }
  
  // ── Step 3: Scan all TS/TSX files ────────────────────────────────────────
  function scanDir(dir) {
    if (!fs.existsSync(dir)) return
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === 'node_modules' || entry.name === '.git' || 
          entry.name === '.next' || entry.name === 'dist') continue
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) { scanDir(full) }
      else if (/\.(ts|tsx)$/.test(entry.name)) {
        stats.scanned++
        let content = fs.readFileSync(full, 'utf-8')
        let changed = false
        
        for (const [localPath, enginePath] of Object.entries(replacements)) {
          const importRe = new RegExp(
            `(from\\s+['"])${localPath.replace(/\//g, '\\/')}(['"])`, 'g'
          )
          const newContent = content.replace(importRe, `$1${enginePath}$2`)
          if (newContent !== content) {
            changed = true
            content = newContent
          }
        }
        
        if (changed) {
          // Only replace if the engine export exists
          let safe = true
          for (const enginePath of Object.values(replacements)) {
            if (content.includes(enginePath)) {
              // Verify the engine module exists
              const modParts = enginePath.split('/')
              const modFile = path.join(enginePath, 'dist', modParts.slice(1).join('/'), 'index.js')
              const altFile = path.join(enginePath, 'dist', modParts.slice(1).join('/') + '.js')
              if (!fs.existsSync(modFile) && !fs.existsSync(altFile)) {
                // Module might not exist, check main entry
                const mainFile = path.join(enginePath, 'dist', 'index.js')
                if (!fs.existsSync(mainFile)) {
                  safe = false
                }
              }
            }
          }
          
          if (safe) {
            fs.writeFileSync(full, content, 'utf-8')
            stats.patched++
            console.log(`  ✅ ${path.relative(cwd, full)}`)
          } else {
            stats.errors++
            console.log(`  ⚠️  ${path.relative(cwd, full)} — engine module not found, skipping`)
          }
        }
      }
    }
  }
  
  console.log('\n  🔍 Scanning project for YVON imports...\n')
  scanDir(cwd)
  
  // ── Step 4: Summary ──────────────────────────────────────────────────────
  console.log(`\n  📊 ${stats.scanned} files scanned`)
  if (stats.patched > 0) {
    console.log(`  ✅ ${stats.patched} files patched to use @yvon/engine`)
    console.log(`\n  🧪 Run: npm run build   (verify nothing broke)`)
  } else {
    console.log(`  ℹ️  No files needed patching — already using engine or no CIE imports found`)
    console.log(`\n  💡 Tip: Import CIE with: import { buildCieContext } from '@yvon/engine/cie'`)
  }
  if (stats.errors > 0) console.log(`  ⚠️  ${stats.errors} files skipped (engine modules not available)`)
  console.log('')
}

function version() { console.log('YVON Engine v1.3.0') }

// ─── Helpers ───────────────────────────────────────────────────────────────

function mkdir(p) { fs.mkdirSync(p, { recursive: true }) }
function copyDir(s, d) { mkdir(d); for (const e of fs.readdirSync(s, { withFileTypes: true })) { const sp = path.join(s, e.name), dp = path.join(d, e.name); e.isDirectory() ? copyDir(sp, dp) : fs.copyFileSync(sp, dp) } }
function countAgents(d) { if (!fs.existsSync(d)) return '0'; let c = 0; for (const de of fs.readdirSync(d)) { const dp = path.join(d, de); if (fs.statSync(dp).isDirectory()) for (const a of fs.readdirSync(dp)) { if (fs.statSync(path.join(dp, a)).isDirectory()) c++ } } return String(c) }

// ─── Dispatch ──────────────────────────────────────────────────────────────

const cmds = { init, doctor, graph, agents, dashboard, integrate, version }
;(cmds[command] || help)()

function dashboard() {
  console.log('\n  ⚡ Starting TOON Dashboard...\n')
  try {
    const { startDashboard } = require('../dist/dashboard/index.js')
    startDashboard(4200)
    console.log('  ✅ Dashboard running at http://localhost:4200')
    console.log('  Press Ctrl+C to stop\n')
  } catch (e) {
    console.log('  ⚠️  Dashboard not available in this version')
    console.log('  Try: npm install github:OfficialNovizio/YVON-Engine')
  }
}
