// src/adapters/config.ts — Engine configuration resolver
//
// All paths are resolved from yvon.config.json (generated by yvon init)
// or from environment variables. No hardcoded paths.

import { resolve, homedir } from 'os'
import { join } from 'path'
import { existsSync, readFileSync } from 'fs'

export interface EngineConfig {
  // Project paths
  projectRoot: string
  graphifyReport: string
  codegraphReport: string
  agentMemoryDir: string
  hermesMemoryDir: string
  projectClaudePath: string
  ventureDocsDir: string
  
  // CIE settings
  cieEnabled: boolean
  contextCap: number
  adaptiveInjection: boolean
  
  // TOON settings
  toonEnabled: boolean
  toonBidirectional: boolean
}

let cachedConfig: EngineConfig | null = null
let configMtime: number = 0

function detectProjectRoot(): string {
  // Walk up from cwd to find yvon.config.json or package.json
  let dir = process.cwd()
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, 'yvon.config.json'))) return dir
    if (existsSync(join(dir, 'package.json'))) return dir
    const parent = resolve(dir, '..')
    if (parent === dir) break
    dir = parent
  }
  return process.cwd()
}

export function getConfig(): EngineConfig {
  const root = detectProjectRoot()
  const configPath = join(root, 'yvon.config.json')
  
  // Try reading config file
  let fileConfig: Partial<EngineConfig> = {}
  if (existsSync(configPath)) {
    try {
      fileConfig = JSON.parse(readFileSync(configPath, 'utf-8'))
    } catch { /* use defaults */ }
  }
  
  return {
    projectRoot: root,
    graphifyReport: fileConfig.graphifyReport ?? join(root, 'graphify-out', 'GRAPH_REPORT.md'),
    codegraphReport: fileConfig.codegraphReport ?? join(root, 'graphify-out', 'CODEGRAPH_REPORT.md'),
    agentMemoryDir: fileConfig.agentMemoryDir ?? join(root, 'agent-memory'),
    hermesMemoryDir: fileConfig.hermesMemoryDir ?? join(homedir(), '.hermes', 'memories'),
    projectClaudePath: fileConfig.projectClaudePath ?? join(root, 'CLAUDE.md'),
    ventureDocsDir: fileConfig.ventureDocsDir ?? join(root, 'docs', 'ventures'),
    
    cieEnabled: fileConfig.cieEnabled ?? true,
    contextCap: fileConfig.contextCap ?? 2500,
    adaptiveInjection: fileConfig.adaptiveInjection ?? true,
    
    toonEnabled: fileConfig.toonEnabled ?? true,
    toonBidirectional: fileConfig.toonBidirectional ?? true,
  }
}

export function invalidateConfig(): void {
  cachedConfig = null
}
